export interface MonumentType {
    img: string;
    name: string;
}

export const dataMonument: MonumentType[] = [
    { img: '/monument/1.jpg', name: 'Памятник №1' },
    { img: '/monument/2.jpg', name: 'Памятник №2' },
    { img: '/monument/3.jpg', name: 'Памятник №3' },
    { img: '/monument/4.jpg', name: 'Памятник №4' },
    { img: '/monument/5.jpg', name: 'Памятник №5' },
    { img: '/monument/5.jpg', name: 'Памятник №5' },
    { img: '/monument/7.jpg', name: 'Памятник №7' },
    { img: '/monument/8.jpg', name: 'Памятник №8' },
    { img: '/monument/9.jpg', name: 'Памятник №9' },
    { img: '/monument/10.jpg', name: 'Памятник №10' },
    { img: '/monument/11.jpg', name: 'Памятник №11' },
    { img: '/monument/12.jpg', name: 'Памятник №12' },
    { img: '/monument/13.jpg', name: 'Памятник №13'},
    { img: '/monument/14.jpg', name: 'Памятник №14'},
    { img: '/monument/15.jpg', name: 'Памятник №15'},
    { img: '/monument/16.jpg', name: 'Памятник №16'},
    { img: '/monument/17.jpg', name: 'Памятник №17'},
    { img: '/monument/18.jpg', name: 'Памятник №18'},
    { img: '/monument/19.jpg', name: 'Памятник №19'},
    { img: '/monument/20.jpg', name: 'Памятник №20'},
    { img: '/monument/21.jpg', name: 'Памятник №21'},
    { img: '/monument/22.jpg', name: 'Памятник №22'},
    { img: '/monument/23.jpg', name: 'Памятник №23'},
    { img: '/monument/24.jpg', name: 'Памятник №24'},
    { img: '/monument/25.jpg', name: 'Памятник №25'},
    { img: '/monument/26.jpg', name: 'Памятник №26'},
    { img: '/monument/27.jpg', name: 'Памятник №27'},
    { img: '/monument/28.jpg', name: 'Памятник №28'},
    { img: '/monument/29.jpg', name: 'Памятник №29'},
    { img: '/monument/30.jpg', name: 'Памятник №30'},
    { img: '/monument/31.jpg', name: 'Памятник №31'},
    { img: '/monument/32.jpg', name: 'Памятник №32'},
    { img: '/monument/33.jpg', name: 'Памятник №33'},
    { img: '/monument/34.jpg', name: 'Памятник №34'},
    { img: '/monument/35.jpg', name: 'Памятник №35'},
    { img: '/monument/36.jpg', name: 'Памятник №36'},
    { img: '/monument/37.jpg', name: 'Памятник №37'},
    { img: '/monument/38.jpg', name: 'Памятник №38'},
    { img: '/monument/39.jpg', name: 'Памятник №39'},
    { img: '/monument/40.jpg', name: 'Памятник №40'},
    { img: '/monument/41.jpg', name: 'Памятник №41'},
    { img: '/monument/42.jpg', name: 'Памятник №42'},
    { img: '/monument/43.jpg', name: 'Памятник №43'},
    { img: '/monument/44.jpg', name: 'Памятник №44'},
    { img: '/monument/45.jpg', name: 'Памятник №45'},
    { img: '/monument/46.jpg', name: 'Памятник №46'},
    { img: '/monument/47.jpg', name: 'Памятник №47'},
    { img: '/monument/48.jpg', name: 'Памятник №48'},
    { img: '/monument/49.jpg', name: 'Памятник №49'},
    { img: '/monument/50.jpg', name: 'Памятник №50'},
    { img: '/monument/51.jpg', name: 'Памятник №51'},
    { img: '/monument/52.jpg', name: 'Памятник №52'},
    { img: '/monument/53.jpg', name: 'Памятник №53'},
    { img: '/monument/54.jpg', name: 'Памятник №54'},
    { img: '/monument/55.jpg', name: 'Памятник №55'},
    { img: '/monument/56.jpg', name: 'Памятник №56'},
    { img: '/monument/57.jpg', name: 'Памятник №57'},
    { img: '/monument/58.jpg', name: 'Памятник №58'},
    { img: '/monument/59.jpg', name: 'Памятник №59'},
    { img: '/monument/60.jpg', name: 'Памятник №60'},
    { img: '/monument/61.jpg', name: 'Памятник №61'},
    { img: '/monument/62.jpg', name: 'Памятник №62'},
    { img: '/monument/63.jpg', name: 'Памятник №63'},
    { img: '/monument/64.jpg', name: 'Памятник №64'},
    { img: '/monument/65.jpg', name: 'Памятник №65'},
    { img: '/monument/66.jpg', name: 'Памятник №66'},
    { img: '/monument/67.jpg', name: 'Памятник №67'},
    { img: '/monument/68.jpg', name: 'Памятник №68'},
    { img: '/monument/69.jpg', name: 'Памятник №69'},
    { img: '/monument/70.jpg', name: 'Памятник №70'},
    { img: '/monument/71.jpg', name: 'Памятник №71'},
    { img: '/monument/72.jpg', name: 'Памятник №72'},
    { img: '/monument/73.jpg', name: 'Памятник №73'},
    { img: '/monument/74.jpg', name: 'Памятник №74'},
    { img: '/monument/75.jpg', name: 'Памятник №75'},
    { img: '/monument/76.jpg', name: 'Памятник №76'},
    { img: '/monument/77.jpg', name: 'Памятник №77'},
    { img: '/monument/78.jpg', name: 'Памятник №78'},
    { img: '/monument/79.jpg', name: 'Памятник №79'},
    { img: '/monument/80.jpg', name: 'Памятник №80'},
    { img: '/monument/81.jpg', name: 'Памятник №81'},
    { img: '/monument/82.jpg', name: 'Памятник №82'},
    { img: '/monument/83.jpg', name: 'Памятник №83'},
    { img: '/monument/84.jpg', name: 'Памятник №84'},
    { img: '/monument/85.jpg', name: 'Памятник №85'},
    { img: '/monument/86.jpg', name: 'Памятник №86'},
    { img: '/monument/87.jpg', name: 'Памятник №87'},
    { img: '/monument/88.jpg', name: 'Памятник №88'},
    { img: '/monument/89.jpg', name: 'Памятник №89'},
    { img: '/monument/90.jpg', name: 'Памятник №90'},
    { img: '/monument/91.jpg', name: 'Памятник №91'},
    { img: '/monument/92.jpg', name: 'Памятник №92'},
    { img: '/monument/93.jpg', name: 'Памятник №93'},
    { img: '/monument/94.jpg', name: 'Памятник №94'},
    { img: '/monument/95.jpg', name: 'Памятник №95'},
    { img: '/monument/96.jpg', name: 'Памятник №96'},
    { img: '/monument/97.jpg', name: 'Памятник №97'},
    { img: '/monument/98.jpg', name: 'Памятник №98'},
    { img: '/monument/99.jpg', name: 'Памятник №99'},
    { img: '/monument/100.jpg', name: 'Памятник №100'},
    { img: '/monument/101.jpg', name: 'Памятник №101' },
    { img: '/monument/102.jpg', name: 'Памятник №102' },
    { img: '/monument/103.jpg', name: 'Памятник №103' },
    { img: '/monument/104.jpg', name: 'Памятник №104' },
    { img: '/monument/105.jpg', name: 'Памятник №105'},
    { img: '/monument/106.jpg', name: 'Памятник №106'},
    { img: '/monument/107.jpg', name: 'Памятник №107'},
    { img: '/monument/108.jpg', name: 'Памятник №108'},
    { img: '/monument/109.jpg', name: 'Памятник №109'},
    { img: '/monument/110.jpg', name: 'Памятник №110'},
    { img: '/monument/111.jpg', name: 'Памятник №111'},
    { img: '/monument/112.jpg', name: 'Памятник №112'},
    { img: '/monument/113.jpg', name: 'Памятник №113'},
    { img: '/monument/114.jpg', name: 'Памятник №114'},
    { img: '/monument/115.jpg', name: 'Памятник №115'},
    { img: '/monument/116.jpg', name: 'Памятник №116'},
    { img: '/monument/117.jpg', name: 'Памятник №117'},
    { img: '/monument/118.jpg', name: 'Памятник №118'},
    { img: '/monument/119.jpg', name: 'Памятник №119'},
    { img: '/monument/120.jpg', name: 'Памятник №120'},
    { img: '/monument/121.jpg', name: 'Памятник №121'},
    { img: '/monument/122.jpg', name: 'Памятник №122'},
    { img: '/monument/123.jpg', name: 'Памятник №123'},
    { img: '/monument/124.jpg', name: 'Памятник №124'},
    { img: '/monument/125.jpg', name: 'Памятник №125'},
    { img: '/monument/126.jpg', name: 'Памятник №126'},
    { img: '/monument/127.jpg', name: 'Памятник №127'},
    { img: '/monument/128.jpg', name: 'Памятник №128'},
    { img: '/monument/129.jpg', name: 'Памятник №129'},
    { img: '/monument/130.jpg', name: 'Памятник №130'},
    { img: '/monument/131.jpg', name: 'Памятник №131'},
    { img: '/monument/132.jpg', name: 'Памятник №132'},
    { img: '/monument/133.jpg', name: 'Памятник №133'},
    { img: '/monument/134.jpg', name: 'Памятник №134'},
    { img: '/monument/135.jpg', name: 'Памятник №135'},
    { img: '/monument/136.jpg', name: 'Памятник №136'},
    { img: '/monument/137.jpg', name: 'Памятник №137'},
    { img: '/monument/138.jpg', name: 'Памятник №138'},
    { img: '/monument/139.jpg', name: 'Памятник №139'},
    { img: '/monument/140.jpg', name: 'Памятник №140'},
    { img: '/monument/141.jpg', name: 'Памятник №141'},
    { img: '/monument/142.jpg', name: 'Памятник №142'},
    { img: '/monument/143.jpg', name: 'Памятник №143'},
    { img: '/monument/144.jpg', name: 'Памятник №144'},
    { img: '/monument/145.jpg', name: 'Памятник №145'},
    { img: '/monument/146.jpg', name: 'Памятник №146'},
    { img: '/monument/147.jpg', name: 'Памятник №147'},
    { img: '/monument/148.jpg', name: 'Памятник №148'},
    { img: '/monument/149.jpg', name: 'Памятник №149'},
    { img: '/monument/150.jpg', name: 'Памятник №150'},
    { img: '/monument/151.jpg', name: 'Памятник №151'},
    { img: '/monument/152.jpg', name: 'Памятник №152'},
    { img: '/monument/153.jpg', name: 'Памятник №153'},
    { img: '/monument/154.jpg', name: 'Памятник №154'},
    { img: '/monument/155.jpg', name: 'Памятник №155'},
    { img: '/monument/156.jpg', name: 'Памятник №156'},
    { img: '/monument/157.jpg', name: 'Памятник №157'},
    { img: '/monument/158.jpg', name: 'Памятник №158'},
    { img: '/monument/159.jpg', name: 'Памятник №159'},
    { img: '/monument/160.jpg', name: 'Памятник №160'},
    { img: '/monument/161.jpg', name: 'Памятник №161'},
    { img: '/monument/162.jpg', name: 'Памятник №162'},
    { img: '/monument/163.jpg', name: 'Памятник №163'},
    { img: '/monument/164.jpg', name: 'Памятник №164'},
    { img: '/monument/165.jpg', name: 'Памятник №165'},
    { img: '/monument/166.jpg', name: 'Памятник №166'},
    { img: '/monument/167.jpg', name: 'Памятник №167'},
    { img: '/monument/168.jpg', name: 'Памятник №168'},
    { img: '/monument/169.jpg', name: 'Памятник №169'},
    { img: '/monument/170.jpg', name: 'Памятник №170'},
    { img: '/monument/171.jpg', name: 'Памятник №171'},
    { img: '/monument/172.jpg', name: 'Памятник №172'},
    { img: '/monument/173.jpg', name: 'Памятник №173'},
    { img: '/monument/174.jpg', name: 'Памятник №174'},
    { img: '/monument/175.jpg', name: 'Памятник №175'},
    { img: '/monument/176.jpg', name: 'Памятник №176'},
    { img: '/monument/177.jpg', name: 'Памятник №177'},
    { img: '/monument/178.jpg', name: 'Памятник №178'},
    { img: '/monument/179.jpg', name: 'Памятник №179'},
    { img: '/monument/180.jpg', name: 'Памятник №180'},
    { img: '/monument/181.jpg', name: 'Памятник №181'},
    { img: '/monument/182.jpg', name: 'Памятник №182'},
    { img: '/monument/183.jpg', name: 'Памятник №183'},
    { img: '/monument/184.jpg', name: 'Памятник №184'},
    { img: '/monument/185.jpg', name: 'Памятник №185'},
    { img: '/monument/186.jpg', name: 'Памятник №186'},
    { img: '/monument/187.jpg', name: 'Памятник №187'},
    { img: '/monument/188.jpg', name: 'Памятник №188'},
    { img: '/monument/189.jpg', name: 'Памятник №189'},
    { img: '/monument/190.jpg', name: 'Памятник №190'},
    { img: '/monument/191.jpg', name: 'Памятник №191'},
    { img: '/monument/192.jpg', name: 'Памятник №192'},
    { img: '/monument/193.jpg', name: 'Памятник №193'},
    { img: '/monument/194.jpg', name: 'Памятник №194'},
    { img: '/monument/195.jpg', name: 'Памятник №195'},
    { img: '/monument/196.jpg', name: 'Памятник №196'},
    { img: '/monument/197.jpg', name: 'Памятник №197'},
    { img: '/monument/198.jpg', name: 'Памятник №198'},
    { img: '/monument/199.jpg', name: 'Памятник №199'},
    { img: '/monument/200.jpg', name: 'Памятник №200'},
    { img: '/monument/201.jpg', name: 'Памятник №201'},
    { img: '/monument/202.jpg', name: 'Памятник №202'},
    { img: '/monument/203.jpg', name: 'Памятник №203'},
    { img: '/monument/204.jpg', name: 'Памятник №204'},
    { img: '/monument/205.jpg', name: 'Памятник №205'},
    { img: '/monument/206.jpg', name: 'Памятник №206'},
    { img: '/monument/207.jpg', name: 'Памятник №207'},
    { img: '/monument/208.jpg', name: 'Памятник №208'},
    { img: '/monument/209.jpg', name: 'Памятник №209'},
    { img: '/monument/210.jpg', name: 'Памятник №210'},
];